version: 2.1

jobs:
  ui-tests:
    docker:
      - image: cimg/node:20.5-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install && cd UI
      - run:
          name: Run UI tests
          command: cd UI && npx nightwatch ./ui_tests

  api-tests:
    docker:
      - image: cimg/node:20.5-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install && cd API
      - run:
          name: Run API tests
          command: cd API && npm test

workflows:
  build-and-test:
    jobs:
      - ui-tests
      - api-tests
