version: 2.1

jobs:
  ui-tests:
    docker:
      - image: cimg/node:20.5-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install && cd UI
      - run:
          name: Install chromedriver
          command:
            CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
            curl -sS -o - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > /tmp/google-chrome-stable_current_amd64.deb
            sudo dpkg -i /tmp/google-chrome-stable_current_amd64.deb || sudo apt-get -fy install
            sudo apt-get install -y unzip
            curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
            sudo unzip /tmp/chromedriver_linux64.zip chromedriver -d /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
      - run:
          name: Run UI tests
          command: cd UI && npx nightwatch ./ui_tests

  api-tests:
    docker:
      - image: cimg/node:20.5-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install && cd API
      - run:
          name: Run API tests
          command: cd API && npm test

workflows:
  build-and-test:
    jobs:
      - ui-tests
      - api-tests
